name: hne_futures_task
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  dio: ^5.6.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.3

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  mocktail: ^1.0.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

